### ISSUE TITLE
Self Host Installation

### ISSUE THREAD

**Issue by saliksik** [Dhravya/markdowner#2]
Hello!

I have tried your self-host installation but its not working, there are also missing dependencies (@cloudflare/puppeteer, react-tweet). Is it possible we can polish the self-host installation guide and make improvements also on the wrangler.toml file.

Thank you.

**Comment by xwooh** [comment]
I encountered the same problem. How did you resolve it in the end?

**Comment by aleksa-codes** [comment]
Maybe a little bit too late of an answer, but what you have to do is go into the `src` of the project:
```bash
cd src
```
then do:
```bash
npm int
```
then add the dependencies:
```bash
npm install @cloudflare/puppeteer --save-dev
```
```bash
npm install react-tweet
```
This worked in my case, and then you can:
```bash
npm run deploy
```
